const DTC_DB = {
  codes: {
    // MOTEUR ESSENCE
    "P0001": { category: "Moteur", system: "Circuit régulateur débit carburant A", severity: "Moyenne", brands: ["Peugeot", "Renault", "Citroën", "BMW", "Mercedes"] },
    "P0011": { category: "Moteur", system: "Calage arbre à cames A - Avance excessive", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "P0016": { category: "Moteur", system: "Corrélation position vilebrequin/arbre à cames", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Ford"] },
    "P0087": { category: "Moteur", system: "Pression rail carburant trop basse", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Mercedes"] },
    "P0088": { category: "Moteur", system: "Pression rail carburant trop élevée", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0089": { category: "Moteur", system: "Performances régulateur pression carburant", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0101": { category: "Moteur", system: "Problème débitmètre air massique", severity: "Faible", brands: ["Peugeot", "Renault", "Volkswagen", "BMW"] },
    "P0113": { category: "Moteur", system: "Circuit capteur température air admission haut", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "P0117": { category: "Moteur", system: "Circuit capteur température liquide refroidissement bas", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0121": { category: "Moteur", system: "Circuit capteur position papillon", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0130": { category: "Moteur", system: "Circuit sonde lambda rangée 1 capteur 1", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0171": { category: "Moteur", system: "Mélange trop pauvre rangée 1", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "P0172": { category: "Moteur", system: "Mélange trop riche rangée 1", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0201": { category: "Moteur", system: "Circuit injecteur cylindre 1", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0219": { category: "Moteur", system: "Régime moteur excessif", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0234": { category: "Moteur", system: "Suralimentation - Pression turbo excessive", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "P0299": { category: "Moteur", system: "Sous-pression turbo/suralimentation", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "P0300": { category: "Moteur", system: "Ratés d'allumage aléatoires/multiples cylindres", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "P0301": { category: "Moteur", system: "Ratés d'allumage cylindre 1", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0325": { category: "Moteur", system: "Circuit capteur de cliquetis 1", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0335": { category: "Moteur", system: "Circuit capteur position vilebrequin", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0340": { category: "Moteur", system: "Circuit capteur position arbre à cames", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0351": { category: "Moteur", system: "Circuit bobine d'allumage A primaire/secondaire", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0410": { category: "Moteur", system: "Circuit système air secondaire", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0420": { category: "Moteur", system: "Efficacité catalyseur inférieure au seuil", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "P0441": { category: "Moteur", system: "Débit incorrect système EVAP", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "P0455": { category: "Moteur", system: "Fuite importante système EVAP", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "P0480": { category: "Moteur", system: "Circuit ventilateur refroidissement 1", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0500": { category: "Moteur", system: "Circuit capteur vitesse véhicule", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0562": { category: "Moteur", system: "Tension système basse", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0606": { category: "Moteur", system: "Processeur calculateur moteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P062F": { category: "Moteur", system: "Mémoire morte EEPROM/Flash", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0700": { category: "Boîte", system: "Circuit commande boîte de vitesses", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P1000": { category: "Moteur", system: "Test OBD non terminé", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    
    // Code spécifique demandé par l'utilisateur
    "P2002": { category: "Moteur", system: "Efficacité filtre particules inférieure seuil (Banque 1)", severity: "Élevée", brands: ["Peugeot", "Renault", "Opel", "Citroën", "BMW"] },
    "P200E": { category: "Moteur", system: "Température filtre particules trop élevée (Banque 1)", severity: "Élevée", brands: ["Peugeot", "Renault", "Opel", "Citroën", "BMW", "Volkswagen"], description: "Problème courant sur 3008, 5008, Insignia - Température FAP excessive" },
    "P200F": { category: "Moteur", system: "Température filtre particules trop élevée (Banque 2)", severity: "Élevée", brands: ["Peugeot", "Renault", "Opel", "BMW"] },
    "P2015": { category: "Moteur", system: "Capteur position collecteur admission", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P20EE": { category: "Moteur", system: "Efficacité système NOx inférieure seuil", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "P2262": { category: "Moteur", system: "Pression turbo non détectée", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P2263": { category: "Moteur", system: "Performances turbo/suralimentation", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P242F": { category: "Moteur", system: "Restriction filtre particules - régénération forcée", severity: "Élevée", brands: ["Peugeot", "Renault", "Opel", "Citroën"] },
    "P2453": { category: "Moteur", system: "Capteur pression différentielle FAP", severity: "Moyenne", brands: ["Peugeot", "Renault", "Opel", "Citroën"] },
    "P2454": { category: "Moteur", system: "Circuit capteur pression FAP bas", severity: "Moyenne", brands: ["Peugeot", "Renault", "Opel"] },
    "P2457": { category: "Moteur", system: "EGR refroidissement efficacité", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P2463": { category: "Moteur", system: "Filtre particules encrassement", severity: "Élevée", brands: ["Peugeot", "Renault", "Opel", "Citroën"] },
    "P2563": { category: "Moteur", system: "Circuit commande turbo", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P2602": { category: "Moteur", system: "Circuit pompe liquide refroidissement", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    
    // DIESEL
    "P0046": { category: "Moteur Diesel", system: "Circuit commande turbo géométrie variable", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "P0068": { category: "Moteur Diesel", system: "Corrélation débitmètre/papillon/pression admission", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0087": { category: "Moteur Diesel", system: "Pression rail carburant trop basse", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0088": { category: "Moteur Diesel", system: "Pression rail carburant trop élevée", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0093": { category: "Moteur Diesel", system: "Fuite importante circuit carburant", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0193": { category: "Moteur Diesel", system: "Circuit capteur pression rail haut", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0201": { category: "Moteur Diesel", system: "Circuit injecteur cylindre 1", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0219": { category: "Moteur Diesel", system: "Régime moteur excessif", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0234": { category: "Moteur Diesel", system: "Suralimentation excessive", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0299": { category: "Moteur Diesel", system: "Sous-pression turbo", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0380": { category: "Moteur Diesel", system: "Circuit préchauffage bougies", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0400": { category: "Moteur Diesel", system: "Circuit recirculation gaz EGR", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0401": { category: "Moteur Diesel", system: "Débit EGR insuffisant", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0402": { category: "Moteur Diesel", system: "Débit EGR excessif", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0403": { category: "Moteur Diesel", system: "Circuit commande vanne EGR", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0470": { category: "Moteur Diesel", system: "Circuit capteur pression échappement", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0488": { category: "Moteur Diesel", system: "Circuit commande vanne EGR plage/performance", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P1166": { category: "Moteur Diesel", system: "Capteur température carburant", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P1197": { category: "Moteur Diesel", system: "Niveau additif FAP bas", severity: "Moyenne", brands: ["Peugeot", "Renault", "Citroën", "Opel"] },
    "P1247": { category: "Moteur Diesel", system: "Pression turbo faible", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P1351": { category: "Moteur Diesel", system: "Circuit bougies préchauffage", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P1447": { category: "Moteur Diesel", system: "Système EGR débit insuffisant", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P1456": { category: "Moteur Diesel", system: "Niveau additif FAP très bas", severity: "Élevée", brands: ["Peugeot", "Renault", "Citroën"] },
    "P2002": { category: "Moteur Diesel", system: "Efficacité FAP inférieure seuil", severity: "Élevée", brands: ["Peugeot", "Renault", "Opel", "Citroën"] },
    "P200E": { category: "Moteur Diesel", system: "Température FAP trop élevée", severity: "Élevée", brands: ["Peugeot", "Renault", "Opel", "Citroën", "BMW"] },
    "P2015": { category: "Moteur Diesel", system: "Capteur position collecteur admission", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P20EE": { category: "Moteur Diesel", system: "Efficacité système NOx", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P2262": { category: "Moteur Diesel", system: "Pression turbo non détectée", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P242F": { category: "Moteur Diesel", system: "Restriction FAP", severity: "Élevée", brands: ["Peugeot", "Renault", "Opel", "Citroën"] },
    "P2453": { category: "Moteur Diesel", system: "Capteur pression différentielle FAP", severity: "Moyenne", brands: ["Peugeot", "Renault", "Opel"] },
    "P2463": { category: "Moteur Diesel", system: "FAP encrassement", severity: "Élevée", brands: ["Peugeot", "Renault", "Opel"] },
    "P2563": { category: "Moteur Diesel", system: "Circuit commande turbo", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    
    // BOÎTE DE VITESSES
    "P0700": { category: "Boîte", system: "Circuit commande boîte de vitesses", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "P0705": { category: "Boîte", system: "Circuit capteur position sélecteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0715": { category: "Boîte", system: "Circuit capteur vitesse arbre primaire", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0720": { category: "Boîte", system: "Circuit capteur vitesse arbre secondaire", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0730": { category: "Boîte", system: "Rapport incorrect", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0740": { category: "Boîte", system: "Circuit convertisseur de couple", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0750": { category: "Boîte", system: "Électrovanne A commande", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0755": { category: "Boîte", system: "Électrovanne B commande", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0760": { category: "Boîte", system: "Électrovanne C commande", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0770": { category: "Boîte", system: "Électrovanne E commande", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0780": { category: "Boîte", system: "Problème passage rapport", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0841": { category: "Boîte", system: "Circuit capteur pression hydraulique", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0842": { category: "Boîte", system: "Circuit capteur pression hydraulique bas", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0868": { category: "Boîte", system: "Pression fluide boîte basse", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0882": { category: "Boîte", system: "Alimentation calculateur boîte basse", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0897": { category: "Boîte", system: "Dégradation fluide boîte", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P0962": { category: "Boîte", system: "Circuit commande pression électrovanne A bas", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0963": { category: "Boîte", system: "Circuit commande pression électrovanne A haut", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0973": { category: "Boîte", system: "Circuit électrovanne A commande bas", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0974": { category: "Boîte", system: "Circuit électrovanne A commande haut", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0976": { category: "Boîte", system: "Circuit électrovanne B commande bas", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0977": { category: "Boîte", system: "Circuit électrovanne B commande haut", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0982": { category: "Boîte", system: "Circuit capteur pression fluide bas", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0983": { category: "Boîte", system: "Circuit capteur pression fluide haut", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P1769": { category: "Boîte", system: "Problème électrovanne modulation pression", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P1776": { category: "Boîte", system: "Problème temporisateur embrayage", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P1811": { category: "Boîte", system: "Adaptation pression ligne trop longue", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "P1860": { category: "Boîte", system: "Circuit embrayage convertisseur couple", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P2714": { category: "Boîte", system: "Électrovanne D performance", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P2715": { category: "Boîte", system: "Électrovanne D bloquée ouverte", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P2716": { category: "Boîte", system: "Électrovanne D bloquée fermée", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P2763": { category: "Boîte", system: "Circuit pompe fluide boîte haut", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P2764": { category: "Boîte", system: "Circuit pompe fluide boîte bas", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P2769": { category: "Boîte", system: "Circuit électrovanne commande couple bas", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P2770": { category: "Boîte", system: "Circuit électrovanne commande couple haut", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    
    // TRANSMISSION/PONT
    "C1201": { category: "Transmission", system: "Circuit moteur - Désactivation DTC", severity: "Élevée", brands: ["Toyota", "Lexus"] },
    "C1241": { category: "Transmission", system: "Basse tension alimentation", severity: "Élevée", brands: ["Toyota", "Lexus"] },
    "C1249": { category: "Transmission", system: "Pression pompe hybride excessive", severity: "Élevée", brands: ["Toyota", "Lexus"] },
    "C1310": { category: "Transmission", system: "Résultat capteur angle direction", severity: "Moyenne", brands: ["Toyota", "Lexus"] },
    "P0882": { category: "Transmission", system: "Alimentation calculateur boîte basse", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P0883": { category: "Transmission", system: "Alimentation calculateur boîte intermittente", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "P1860": { category: "Transmission", system: "Circuit embrayage convertisseur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    
    // FREINAGE/ABS
    "C0035": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue avant gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "C0040": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue avant droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "C0045": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue arrière gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "C0050": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue arrière droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "C0110": { category: "Freinage/ABS", system: "Circuit pompe ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0121": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0128": { category: "Freinage/ABS", system: "Niveau liquide de frein bas", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0131": { category: "Freinage/ABS", system: "Circuit pression frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0141": { category: "Freinage/ABS", system: "Circuit électrovanne traction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0151": { category: "Freinage/ABS", system: "Circuit électrovanne stabilité", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0161": { category: "Freinage/ABS", system: "Circuit électrovanne ABS gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0171": { category: "Freinage/ABS", system: "Circuit électrovanne ABS droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0196": { category: "Freinage/ABS", system: "Capteur lacet", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C0200": { category: "Freinage/ABS", system: "Circuit moteur roue avant gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0205": { category: "Freinage/ABS", system: "Circuit moteur roue avant droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0210": { category: "Freinage/ABS", system: "Circuit moteur roue arrière gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0215": { category: "Freinage/ABS", system: "Circuit moteur roue arrière droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0221": { category: "Freinage/ABS", system: "Circuit moteur roue avant gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0226": { category: "Freinage/ABS", system: "Circuit moteur roue avant droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0231": { category: "Freinage/ABS", system: "Circuit moteur roue arrière gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0236": { category: "Freinage/ABS", system: "Circuit moteur roue arrière droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0241": { category: "Freinage/ABS", system: "Circuit moteur roue avant gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0245": { category: "Freinage/ABS", system: "Circuit moteur roue avant droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0265": { category: "Freinage/ABS", system: "Circuit relais pompe ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0267": { category: "Freinage/ABS", system: "Pompe ABS bloquée", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0268": { category: "Freinage/ABS", system: "Pompe ABS en marche permanente", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0274": { category: "Freinage/ABS", system: "Circuit pompe ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0283": { category: "Freinage/ABS", system: "Circuit électrovanne traction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0286": { category: "Freinage/ABS", system: "Circuit électrovanne traction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0288": { category: "Freinage/ABS", system: "Circuit électrovanne traction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0290": { category: "Freinage/ABS", system: "Perte freinage", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0291": { category: "Freinage/ABS", system: "Pression frein basse", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0292": { category: "Freinage/ABS", system: "Circuit électrovanne frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0293": { category: "Freinage/ABS", system: "Circuit électrovanne frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0294": { category: "Freinage/ABS", system: "Circuit électrovanne frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0296": { category: "Freinage/ABS", system: "Circuit électrovanne frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0297": { category: "Freinage/ABS", system: "Circuit électrovanne frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0298": { category: "Freinage/ABS", system: "Circuit électrovanne frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0300": { category: "Freinage/ABS", system: "Circuit moteur roue arrière gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0305": { category: "Freinage/ABS", system: "Circuit moteur roue arrière droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0325": { category: "Freinage/ABS", system: "Circuit moteur roue arrière gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0327": { category: "Freinage/ABS", system: "Circuit moteur roue arrière gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0357": { category: "Freinage/ABS", system: "Circuit commutateur frein de stationnement", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C0367": { category: "Freinage/ABS", system: "Circuit capteur température frein", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C0374": { category: "Freinage/ABS", system: "Circuit électrovanne différentiel", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0379": { category: "Freinage/ABS", system: "Circuit électrovanne différentiel", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0455": { category: "Freinage/ABS", system: "Circuit moteur direction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0460": { category: "Freinage/ABS", system: "Circuit moteur direction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0467": { category: "Freinage/ABS", system: "Circuit moteur direction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0472": { category: "Freinage/ABS", system: "Circuit moteur direction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0491": { category: "Freinage/ABS", system: "Circuit moteur direction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0496": { category: "Freinage/ABS", system: "Circuit moteur direction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0550": { category: "Freinage/ABS", system: "Circuit calculateur ESP", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0558": { category: "Freinage/ABS", system: "Circuit calculateur ESP", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0561": { category: "Freinage/ABS", system: "Système ABS désactivé", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0569": { category: "Freinage/ABS", system: "Configuration électronique", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C0577": { category: "Freinage/ABS", system: "Circuit commutateur mode traction", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C0586": { category: "Freinage/ABS", system: "Circuit commutateur mode traction", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C0710": { category: "Freinage/ABS", system: "Circuit commutateur position direction", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C0750": { category: "Freinage/ABS", system: "Circuit communication dispositif frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0755": { category: "Freinage/ABS", system: "Circuit communication dispositif frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0760": { category: "Freinage/ABS", system: "Circuit communication dispositif frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0765": { category: "Freinage/ABS", system: "Circuit communication dispositif frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0775": { category: "Freinage/ABS", system: "Circuit capteur hauteur véhicule", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C0785": { category: "Freinage/ABS", system: "Circuit moteur hauteur véhicule", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C0790": { category: "Freinage/ABS", system: "Circuit commutateur hauteur véhicule", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C0800": { category: "Freinage/ABS", system: "Circuit alimentation calculateur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0896": { category: "Freinage/ABS", system: "Tension calculateur basse", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0899": { category: "Freinage/ABS", system: "Circuit alimentation calculateur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C0900": { category: "Freinage/ABS", system: "Circuit moteur pompe hauteur véhicule", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C1200": { category: "Freinage/ABS", system: "Circuit moteur roue avant gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1201": { category: "Freinage/ABS", system: "Circuit moteur roue avant gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1205": { category: "Freinage/ABS", system: "Circuit moteur roue avant droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1206": { category: "Freinage/ABS", system: "Circuit moteur roue avant droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1210": { category: "Freinage/ABS", system: "Circuit moteur roue arrière gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1211": { category: "Freinage/ABS", system: "Circuit moteur roue arrière gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1215": { category: "Freinage/ABS", system: "Circuit moteur roue arrière droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1216": { category: "Freinage/ABS", system: "Circuit moteur roue arrière droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1217": { category: "Freinage/ABS", system: "Pompe ABS en marche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1218": { category: "Freinage/ABS", system: "Pompe ABS en marche permanente", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1221": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue avant gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1222": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue avant gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1223": { category: "Freinage/ABS", system: "Témoin ABS activé", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1224": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue avant droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1225": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue avant droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1226": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue avant droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1227": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue arrière gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1228": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue arrière gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1229": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue arrière gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1232": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue avant gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1233": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue avant droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1234": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue arrière gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1235": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue arrière droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1236": { category: "Freinage/ABS", system: "Tension batterie basse", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C1237": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue extérieure", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1238": { category: "Freinage/ABS", system: "Circuit capteur vitesse roue extérieure", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1241": { category: "Freinage/ABS", system: "Basse tension alimentation", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1242": { category: "Freinage/ABS", system: "Basse tension alimentation pompe", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1243": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1244": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1245": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1246": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1247": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1248": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1249": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1250": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1251": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1252": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1253": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1254": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1255": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1256": { category: "Freinage/ABS", system: "Circuit électrovanne ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1261": { category: "Freinage/ABS", system: "Circuit moteur électrovanne avant gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1262": { category: "Freinage/ABS", system: "Circuit moteur électrovanne avant droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1263": { category: "Freinage/ABS", system: "Circuit moteur électrovanne arrière gauche", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1264": { category: "Freinage/ABS", system: "Circuit moteur électrovanne arrière droit", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1265": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1266": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1267": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1268": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1269": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1271": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1272": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1273": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1274": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1276": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1277": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1278": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1279": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1281": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1282": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1283": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1284": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1286": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1287": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1288": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1289": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1291": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1292": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1293": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1294": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1295": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1296": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1297": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1298": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1299": { category: "Freinage/ABS", system: "Circuit électrovanne blocage roue", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    
    // ADAS/CAMÉRAS
    "C1001": { category: "ADAS/Caméra", system: "Capteur radar avant", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Mercedes"] },
    "C1002": { category: "ADAS/Caméra", system: "Capteur radar arrière", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1003": { category: "ADAS/Caméra", system: "Caméra avant détection obstacles", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Tesla"] },
    "C1100": { category: "ADAS/Caméra", system: "Système freinage automatique", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1101": { category: "ADAS/Caméra", system: "Aide maintien voie", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1102": { category: "ADAS/Caméra", system: "Régulateur adaptatif", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1103": { category: "ADAS/Caméra", system: "Détection angle mort", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C1104": { category: "ADAS/Caméra", system: "Alerte franchissement ligne", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C1105": { category: "ADAS/Caméra", system: "Reconnaissance panneaux", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "C1106": { category: "ADAS/Caméra", system: "Caméra 360°", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C1107": { category: "ADAS/Caméra", system: "Aide stationnement", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C1108": { category: "ADAS/Caméra", system: "Détection piétons", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1109": { category: "ADAS/Caméra", system: "Vision nocturne", severity: "Moyenne", brands: ["BMW", "Mercedes"] },
    "C1110": { category: "ADAS/Caméra", system: "Caméra recul", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C1111": { category: "ADAS/Caméra", system: "Caméra latérale", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C1112": { category: "ADAS/Caméra", system: "Calibration caméra", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "C1113": { category: "ADAS/Caméra", system: "Obstruction caméra", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C1114": { category: "ADAS/Caméra", system: "Température caméra", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "C1115": { category: "ADAS/Caméra", system: "Communication caméra", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    
    // ÉLECTRONIQUE/CEINTURES
    "B0001": { category: "Électronique/Ceinture", system: "Circuit airbag conducteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "B0002": { category: "Électronique/Ceinture", system: "Circuit airbag passager", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "B0003": { category: "Électronique/Ceinture", system: "Circuit prétensionneur ceinture conducteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "B0004": { category: "Électronique/Ceinture", system: "Circuit prétensionneur ceinture passager", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "B0005": { category: "Électronique/Ceinture", system: "Circuit capteur choc avant", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "B0006": { category: "Électronique/Ceinture", system: "Circuit capteur choc latéral", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "B0007": { category: "Électronique/Ceinture", system: "Circuit airbag rideau", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "B0008": { category: "Électronique/Ceinture", system: "Circuit airbag genoux", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "B0009": { category: "Électronique/Ceinture", system: "Circuit capteur occupation siège", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "B0010": { category: "Électronique/Ceinture", system: "Circuit boucle ceinture conducteur", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "B0011": { category: "Électronique/Ceinture", system: "Circuit boucle ceinture passager", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "B0012": { category: "Électronique/Ceinture", system: "Circuit témoin airbag", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "B0013": { category: "Électronique/Ceinture", system: "Circuit calculateur airbag", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "B0014": { category: "Électronique/Ceinture", system: "Communication calculateur airbag", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "B0015": { category: "Électronique/Ceinture", system: "Circuit alimentation airbag", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    
    // ÉLECTRIQUE/HYBRIDE
    "P0A00": { category: "Électrique/Hybride", system: "Circuit moteur/générateur électronique", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A01": { category: "Électrique/Hybride", system: "Circuit capteur température moteur/générateur", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A02": { category: "Électrique/Hybride", system: "Court-circuit moteur/générateur", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A03": { category: "Électrique/Hybride", system: "Circuit commande moteur/générateur", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A04": { category: "Électrique/Hybride", system: "Circuit capteur courant moteur/générateur", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A05": { category: "Électrique/Hybride", system: "Moteur/générateur 1 hors service", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A06": { category: "Électrique/Hybride", system: "Circuit alimentation moteur/générateur haut", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A07": { category: "Électrique/Hybride", system: "Circuit alimentation moteur/générateur bas", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A08": { category: "Électrique/Hybride", system: "Circuit DC-DC convertisseur", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A09": { category: "Électrique/Hybride", system: "Tension DC-DC convertisseur basse", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A0A": { category: "Électrique/Hybride", system: "Circuit haute tension hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A0B": { category: "Électrique/Hybride", system: "Système hybride batterie basse", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A0C": { category: "Électrique/Hybride", system: "Circuit générateur hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A0D": { category: "Électrique/Hybride", system: "Circuit générateur hybride bas", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A0E": { category: "Électrique/Hybride", system: "Circuit générateur hybride haut", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A0F": { category: "Électrique/Hybride", system: "Démarrage moteur hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A10": { category: "Électrique/Hybride", system: "Circuit système DC-DC", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A11": { category: "Électrique/Hybride", system: "Circuit pompe liquide refroidissement hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A12": { category: "Électrique/Hybride", system: "Circuit refroidissement hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A13": { category: "Électrique/Hybride", system: "Circuit capteur température hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A14": { category: "Électrique/Hybride", system: "Circuit moteur hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A15": { category: "Électrique/Hybride", system: "Circuit générateur hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A16": { category: "Électrique/Hybride", system: "Circuit générateur hybride bas", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A17": { category: "Électrique/Hybride", system: "Circuit générateur hybride haut", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A18": { category: "Électrique/Hybride", system: "Circuit générateur hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A19": { category: "Électrique/Hybride", system: "Circuit générateur hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A1A": { category: "Électrique/Hybride", system: "Circuit générateur hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A1B": { category: "Électrique/Hybride", system: "Circuit générateur hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A1C": { category: "Électrique/Hybride", system: "Circuit générateur hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A1D": { category: "Électrique/Hybride", system: "Circuit générateur hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A1E": { category: "Électrique/Hybride", system: "Circuit générateur hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    "P0A1F": { category: "Électrique/Hybride", system: "Circuit générateur hybride", severity: "Élevée", brands: ["Toyota", "Lexus", "Honda"] },
    
    // SPORADIQUES/MISES À JOUR
    "U0001": { category: "Sporadique/MAJ", system: "Bus CAN haute vitesse", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW", "Volkswagen"] },
    "U0002": { category: "Sporadique/MAJ", system: "Bus CAN haute vitesse performance", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0003": { category: "Sporadique/MAJ", system: "Bus CAN haute vitesse (+)", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0004": { category: "Sporadique/MAJ", system: "Bus CAN haute vitesse (-)", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0005": { category: "Sporadique/MAJ", system: "Bus CAN haute vitesse bas", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0006": { category: "Sporadique/MAJ", system: "Bus CAN basse vitesse", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0007": { category: "Sporadique/MAJ", system: "Bus CAN basse vitesse performance", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0008": { category: "Sporadique/MAJ", system: "Bus CAN basse vitesse (+)", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0009": { category: "Sporadique/MAJ", system: "Bus CAN basse vitesse (-)", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0010": { category: "Sporadique/MAJ", system: "Bus CAN basse vitesse bas", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0100": { category: "Sporadique/MAJ", system: "Perte communication calculateur moteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0101": { category: "Sporadique/MAJ", system: "Perte communication calculateur boîte", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0121": { category: "Sporadique/MAJ", system: "Perte communication calculateur ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0140": { category: "Sporadique/MAJ", system: "Perte communication calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0155": { category: "Sporadique/MAJ", system: "Perte communication calculateur tableau bord", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0164": { category: "Sporadique/MAJ", system: "Perte communication climatisation", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0198": { category: "Sporadique/MAJ", system: "Perte communication module télématique", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0200": { category: "Sporadique/MAJ", system: "Perte communication boîte vitesses", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0201": { category: "Sporadique/MAJ", system: "Perte communication airbag", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0208": { category: "Sporadique/MAJ", system: "Perte communication siège", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0209": { category: "Sporadique/MAJ", system: "Perte communication airbag", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0210": { category: "Sporadique/MAJ", system: "Perte module suspension", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0212": { category: "Sporadique/MAJ", system: "Perte communication volant", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0214": { category: "Sporadique/MAJ", system: "Perte communication verrouillage", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0215": { category: "Sporadique/MAJ", system: "Perte communication porte", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0221": { category: "Sporadique/MAJ", system: "Perte communication portière", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0230": { category: "Sporadique/MAJ", system: "Perte communication hayon", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0235": { category: "Sporadique/MAJ", system: "Perte communication régulateur", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0249": { category: "Sporadique/MAJ", system: "Perte communication module divertissement", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0250": { category: "Sporadique/MAJ", system: "Perte communication module divertissement", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0251": { category: "Sporadique/MAJ", system: "Perte communication module audio", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0252": { category: "Sporadique/MAJ", system: "Perte communication module divertissement", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0253": { category: "Sporadique/MAJ", system: "Perte communication accès véhicule", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0254": { category: "Sporadique/MAJ", system: "Perte communication démarrage", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0255": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0256": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0257": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0258": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0259": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0260": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0261": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0262": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0263": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0264": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0265": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0266": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0267": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0268": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0269": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0270": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0271": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0272": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0273": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0274": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0275": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0276": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0277": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0278": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0279": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0280": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0281": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0282": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0283": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0284": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0285": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0286": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0287": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0288": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0289": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0290": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0291": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0292": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0293": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0294": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0295": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0296": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0297": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0298": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0299": { category: "Sporadique/MAJ", system: "Perte communication interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0300": { category: "Sporadique/MAJ", system: "Incompatibilité logiciel interne", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0301": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur moteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0302": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur boîte", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0303": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur transfert", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0304": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur différentiel", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0305": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0306": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur traction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0307": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur stabilité", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0308": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur propulsion", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0309": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur alternative", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0310": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur moteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0311": { category: "Sporadique/MAJ", system: "Incompatibilité direction assistée", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0312": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0313": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur hybride", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0314": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur 4 roues", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0315": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0316": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur traction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0317": { category: "Sporadique/MAJ", system: "Incompatibilité régulateur vitesse", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0318": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur climatisation", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0319": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur ACC", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0320": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur véhicule", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0321": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur suspension", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0322": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0323": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur divertissement", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0324": { category: "Sporadique/MAJ", system: "Incompatibilité climatisation", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0325": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur climatisation", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0326": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur divertissement", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0327": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur interface", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0328": { category: "Sporadique/MAJ", system: "Incompatibilité capteur direction", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0329": { category: "Sporadique/MAJ", system: "Incompatibilité colonne direction", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0330": { category: "Sporadique/MAJ", system: "Incompatibilité assistance stationnement", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0331": { category: "Sporadique/MAJ", system: "Incompatibilité tableau bord", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0332": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0333": { category: "Sporadique/MAJ", system: "Incompatibilité module accessoire", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0334": { category: "Sporadique/MAJ", system: "Incompatibilité module divertissement", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0335": { category: "Sporadique/MAJ", system: "Incompatibilité interface adaptative", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0336": { category: "Sporadique/MAJ", system: "Incompatibilité communication", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0337": { category: "Sporadique/MAJ", system: "Incompatibilité capteur pression pneus", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0338": { category: "Sporadique/MAJ", system: "Incompatibilité contrôle freinage", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0339": { category: "Sporadique/MAJ", system: "Incompatibilité capteur contenu", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0340": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0341": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0342": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0343": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0344": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0345": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0346": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0347": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0348": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0349": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0350": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0351": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0352": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0353": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0354": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0355": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0356": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0357": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0358": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0359": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0360": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0361": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0362": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0363": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0364": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0365": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0366": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0367": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0368": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0369": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0370": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0371": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0372": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0373": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0374": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0375": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0376": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0377": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0378": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0379": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0380": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0381": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0382": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0383": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0384": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0385": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0386": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0387": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0388": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0389": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0390": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0391": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0392": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0393": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0394": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0395": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0396": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0397": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0398": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0399": { category: "Sporadique/MAJ", system: "Incompatibilité calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0400": { category: "Sporadique/MAJ", system: "Données invalides reçues", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0401": { category: "Sporadique/MAJ", system: "Données invalides calculateur moteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0402": { category: "Sporadique/MAJ", system: "Données invalides calculateur boîte", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0403": { category: "Sporadique/MAJ", system: "Données invalides calculateur transfert", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0404": { category: "Sporadique/MAJ", system: "Données invalides calculateur différentiel", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0405": { category: "Sporadique/MAJ", system: "Données invalides calculateur régulateur", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0406": { category: "Sporadique/MAJ", system: "Données invalides calculateur affichage", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0407": { category: "Sporadique/MAJ", system: "Données invalides calculateur affichage", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0408": { category: "Sporadique/MAJ", system: "Données invalides calculateur affichage", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0409": { category: "Sporadique/MAJ", system: "Données invalides calculateur affichage", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0410": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0411": { category: "Sporadique/MAJ", system: "Données invalides calculateur traction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0412": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0413": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0414": { category: "Sporadique/MAJ", system: "Données invalides calculateur 4 roues", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0415": { category: "Sporadique/MAJ", system: "Données invalides calculateur ABS", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0416": { category: "Sporadique/MAJ", system: "Données invalides calculateur véhicule", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0417": { category: "Sporadique/MAJ", system: "Données invalides calculateur frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0418": { category: "Sporadique/MAJ", system: "Données invalides calculateur frein", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0419": { category: "Sporadique/MAJ", system: "Données invalides calculateur direction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0420": { category: "Sporadique/MAJ", system: "Données invalides calculateur direction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0421": { category: "Sporadique/MAJ", system: "Données invalides calculateur moteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0422": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0423": { category: "Sporadique/MAJ", system: "Données invalides calculateur tableau bord", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0424": { category: "Sporadique/MAJ", system: "Données invalides calculateur climatisation", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0425": { category: "Sporadique/MAJ", system: "Données invalides calculateur climatisation", severity: "Faible", brands: ["Peugeot", "Renault", "BMW"] },
    "U0426": { category: "Sporadique/MAJ", system: "Données invalides calculateur antivol", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0427": { category: "Sporadique/MAJ", system: "Données invalides calculateur antivol", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0428": { category: "Sporadique/MAJ", system: "Données invalides calculateur direction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0429": { category: "Sporadique/MAJ", system: "Données invalides calculateur direction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0430": { category: "Sporadique/MAJ", system: "Données invalides calculateur direction", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0431": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0432": { category: "Sporadique/MAJ", system: "Données invalides calculateur suspension", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0433": { category: "Sporadique/MAJ", system: "Données invalides calculateur suspension", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0434": { category: "Sporadique/MAJ", system: "Données invalides calculateur moteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0435": { category: "Sporadique/MAJ", system: "Données invalides calculateur moteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0436": { category: "Sporadique/MAJ", system: "Données invalides calculateur moteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0437": { category: "Sporadique/MAJ", system: "Données invalides calculateur moteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0438": { category: "Sporadique/MAJ", system: "Données invalides calculateur moteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0439": { category: "Sporadique/MAJ", system: "Données invalides calculateur moteur", severity: "Élevée", brands: ["Peugeot", "Renault", "BMW"] },
    "U0440": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0441": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0442": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0443": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0444": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0445": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0446": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0447": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0448": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0449": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0450": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0451": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0452": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0453": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0454": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0455": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0456": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0457": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0458": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0459": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0460": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0461": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0462": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0463": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0464": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0465": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0466": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0467": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0468": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0469": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0470": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0471": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0472": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0473": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0474": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0475": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0476": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0477": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0478": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0479": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0480": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0481": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0482": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0483": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0484": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0485": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0486": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0487": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0488": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0489": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0490": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0491": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0492": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0493": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0494": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0495": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0496": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0497": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0498": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] },
    "U0499": { category: "Sporadique/MAJ", system: "Données invalides calculateur carrosserie", severity: "Moyenne", brands: ["Peugeot", "Renault", "BMW"] }
  },

  async init() {
    const dtcList = await DB.getAll('dtcCodes');
    if (dtcList.length === 0) {
      await this.populate();
    }
  },

    async populate() {
    console.log("🔄 Peuplement base DTC...");
    const items = [];
    for (const code in this.codes) {
      const dtc = this.codes[code];
      items.push({
        code: code,
        category: dtc.category,
        system: dtc.system,
        severity: dtc.severity,
        brands: dtc.brands,
        description: dtc.description || null,
        addedAt: Date.now()
      });
    }
    await DB.bulkAdd('dtcCodes', items);
    console.log(`✅ ${items.length} codes DTC ajoutés`);
  },);
      count++;
    }

    console.log(`✅ ${count} codes DTC ajoutés`);
  },

  async getByCode(code) {
    return await DB.get('dtcCodes', code);
  },

  async search(query) {
    const all = await DB.getAll('dtcCodes');
    const q = query.toLowerCase().trim();
    if (!q) return [];

    return all.filter(dtc =>
      dtc.code.toLowerCase().includes(q) ||
      dtc.system.toLowerCase().includes(q) ||
      dtc.category.toLowerCase().includes(q)
    );
  },

  async getByBrand(brand) {
    const all = await DB.getAll('dtcCodes');
    return all.filter(dtc => dtc.brands.includes(brand));
  },

  async getBySeverity(severity) {
    return await DB.getByIndex('dtcCodes', 'severity', severity);
  },

  async getByCategory(category) {
    return await DB.getByIndex('dtcCodes', 'category', category);
  }
};
