// ============================================================
// AUTO-DIAGNOSTIC PRO - RAPPELS + PANNES MASSIVES
// Chaque motorisation de chaque modèle retourne ses pannes
// connues + codes DTC (générateur par famille moteur)
// ============================================================

const RECALLS_DB = {

  sources: {
    NHTSA: { name: "NHTSA (USA)" }, SAFETY_GATE: { name: "Safety Gate (UE)" },
    RAPPEL_CONSO: { name: "Rappel Conso (FR)" }, SPECIALISTES: { name: "Sites spécialisés" }
  },

  recalls: [
    { id: 1, brand: "Peugeot", model: "3008", years: [2017,2018,2019], source: "RAPPEL_CONSO", severity: "Élevée", title: "Risque incendie turbo 1.2 PureTech", description: "Fuite d'huile turbo pouvant provoquer un incendie.", dtcRelated: ["P0299","P2262","P0234"], repairAction: "Remplacement turbo + durites", datePublished: "2023-05-15" },
    { id: 2, brand: "Peugeot", model: "3008", years: [2019,2020,2021], source: "RAPPEL_CONSO", severity: "Élevée", title: "GPF encrassement (P2002/P200E)", description: "Encrassement prématuré du filtre à particules essence.", dtcRelated: ["P2002","P242F","P2453","P2463","P200E"], repairAction: "Nettoyage GPF + MAJ ECU", datePublished: "2023-02-28" },
    { id: 3, brand: "Peugeot", model: "3008", years: [2020,2021], source: "SAFETY_GATE", severity: "Moyenne", title: "Boîte EAT8 à-coups à froid", description: "Bug logiciel boîte automatique EAT8.", dtcRelated: ["P0700","P0715","P0720"], repairAction: "MAJ calculateur boîte", datePublished: "2023-08-10" },
    { id: 4, brand: "Peugeot", model: "5008", years: [2017,2018,2019], source: "RAPPEL_CONSO", severity: "Élevée", title: "Fuite liquide frein maître-cylindre", description: "Perte d'efficacité freinage.", dtcRelated: ["C1283","C0131"], repairAction: "Remplacement maître-cylindre", datePublished: "2023-03-22" },
    { id: 5, brand: "Peugeot", model: "5008", years: [2020,2021,2022], source: "NHTSA", severity: "Moyenne", title: "Radar ADAS fausses alertes", description: "Freinage d'urgence intempestif.", dtcRelated: ["C1001","C1100","C1102"], repairAction: "Calibration radar", datePublished: "2023-07-14" },
    { id: 6, brand: "Peugeot", model: "208", years: [2019,2020], source: "RAPPEL_CONSO", severity: "Élevée", title: "Courroie distribution 1.2 PureTech", description: "Dégradation courroie immergée, crépine bouchée.", dtcRelated: ["P0016","P0340","P0335"], repairAction: "Kit distribution + crépine", datePublished: "2023-09-01" },
    { id: 7, brand: "Peugeot", model: "208", years: [2020,2021], source: "SPECIALISTES", severity: "Moyenne", title: "e-208 batterie traction", description: "Perte autonomie + erreur HT.", dtcRelated: ["P0A0A","P0A0B","P0A1F"], repairAction: "MAJ BMS", datePublished: "2024-02-18" },
    { id: 8, brand: "Peugeot", model: "508", years: [2018,2019], source: "SAFETY_GATE", severity: "Élevée", title: "Fuite carburant 1.5 BlueHDi", description: "Risque incendie rampe injection.", dtcRelated: ["P0087","P0093","P0193"], repairAction: "Rampe + durites", datePublished: "2022-06-30" },
    { id: 9, brand: "Peugeot", model: "308", years: [2017,2018], source: "RAPPEL_CONSO", severity: "Élevée", title: "Embrayage boîte double embrayage", description: "À-coups, patinage.", dtcRelated: ["P0700","P0740","P0868"], repairAction: "Kit embrayage + volant", datePublished: "2022-10-11" },
    { id: 10, brand: "Renault", model: "Clio V", years: [2019,2020], source: "RAPPEL_CONSO", severity: "Élevée", title: "Fuite injecteurs 1.0 TCe", description: "Risque incendie.", dtcRelated: ["P0201","P0093"], repairAction: "Injecteurs + joints", datePublished: "2023-01-10" },
    { id: 11, brand: "Renault", model: "Captur II", years: [2020,2021], source: "SAFETY_GATE", severity: "Élevée", title: "Freinage E-Tech pédale dure", description: "Perte assistance freinage mode électrique.", dtcRelated: ["C1283","P0A0F"], repairAction: "MAJ ABS/ESP", datePublished: "2023-05-30" },
    { id: 12, brand: "Renault", model: "Zoe", years: [2019,2020,2021], source: "RAPPEL_CONSO", severity: "Élevée", title: "Chargeur batterie 52 kWh", description: "Anomalie chargeur.", dtcRelated: ["P0A08","P0A09","P0A0B"], repairAction: "MAJ BMS + chargeur", datePublished: "2022-09-15" },
    { id: 13, brand: "Renault", model: "R5 E-Tech", years: [2024,2025], source: "SPECIALISTES", severity: "Moyenne", title: "Recharge DC instable", description: "Coupures charge rapide.", dtcRelated: ["P0A08","P0A09"], repairAction: "MAJ logiciel charge", datePublished: "2025-03-10" },
    { id: 14, brand: "Renault", model: "R4 E-Tech", years: [2025], source: "SPECIALISTES", severity: "Moyenne", title: "Calibration BMS", description: "Estimation SOC imprécise.", dtcRelated: ["P0A0B","P0A1F"], repairAction: "MAJ BMS", datePublished: "2025-06-20" },
    { id: 15, brand: "Renault", model: "Koleos", years: [2017,2018], source: "SAFETY_GATE", severity: "Élevée", title: "Boîte CVT X-Tronic", description: "À-coups, surchauffe.", dtcRelated: ["P0740","P0700","P0868"], repairAction: "Convertisseur + vidange", datePublished: "2022-08-08" },
    { id: 16, brand: "Renault", model: "Talisman", years: [2017,2018], source: "SPECIALISTES", severity: "Moyenne", title: "Vanne EGR 1.7 Blue dCi", description: "Encrassement, perte puissance.", dtcRelated: ["P0400","P0401","P0402"], repairAction: "Nettoyage EGR", datePublished: "2023-06-20" },
    { id: 17, brand: "Citroën", model: "C5 Aircross", years: [2019,2020], source: "RAPPEL_CONSO", severity: "Élevée", title: "Courroie distribution 1.2 PureTech", description: "Courroie dans l'huile.", dtcRelated: ["P0016","P0340"], repairAction: "Kit distribution", datePublished: "2023-09-12" },
    { id: 18, brand: "Citroën", model: "ë-C4", years: [2021,2022], source: "SPECIALISTES", severity: "Moyenne", title: "Charge AC lente", description: "Bug communication chargeur.", dtcRelated: ["P0A08"], repairAction: "MAJ chargeur", datePublished: "2024-01-30" },
    { id: 19, brand: "DS", model: "DS 7", years: [2019,2020], source: "RAPPEL_CONSO", severity: "Élevée", title: "Connecteur recharge E-Tense", description: "Surchauffe prise domestique.", dtcRelated: ["P0A08"], repairAction: "Câble + connecteur", datePublished: "2023-08-22" },
    { id: 20, brand: "Volkswagen", model: "Golf VII", years: [2017,2018], source: "SAFETY_GATE", severity: "Élevée", title: "Chaîne distribution 1.4 TSI", description: "Risque casse moteur EA211.", dtcRelated: ["P0016","P0340","P0335"], repairAction: "Chaîne + tendeur", datePublished: "2022-05-20" },
    { id: 21, brand: "Volkswagen", model: "Tiguan II", years: [2017,2018,2019], source: "NHTSA", severity: "Élevée", title: "DSG mécatronique", description: "Perte propulsion.", dtcRelated: ["P0700","P0715","P0720","P0842"], repairAction: "Mécatronique", datePublished: "2022-11-10" },
    { id: 22, brand: "Volkswagen", model: "Taigo", years: [2021,2022], source: "SPECIALISTES", severity: "Faible", title: "Infotainment/ACC bugs", description: "Écran noir, régulateur inerte.", dtcRelated: ["U0250","C1102"], repairAction: "MAJ logiciel", datePublished: "2023-04-05" },
    { id: 23, brand: "Volkswagen", model: "ID.4", years: [2020,2021], source: "RAPPEL_CONSO", severity: "Élevée", title: "Arrêt propulsion logiciel", description: "Bug logiciel critique.", dtcRelated: ["P0A1F","U0100"], repairAction: "MAJ véhicule", datePublished: "2022-07-25" },
    { id: 24, brand: "Volkswagen", model: "ID.5", years: [2022,2023], source: "RAPPEL_CONSO", severity: "Élevée", title: "Arrêt propulsion logiciel", description: "Même campagne que ID.4/ID.3.", dtcRelated: ["P0A1F","U0100"], repairAction: "MAJ véhicule", datePublished: "2022-07-25" },
    { id: 25, brand: "Volkswagen", model: "Passat B8", years: [2017,2018], source: "SAFETY_GATE", severity: "Élevée", title: "Injecteurs 2.0 TDI", description: "Risque incendie.", dtcRelated: ["P0201","P0202","P0203"], repairAction: "Injecteurs", datePublished: "2022-04-15" },
    { id: 26, brand: "BMW", model: "Série 3 (G20)", years: [2019,2020], source: "NHTSA", severity: "Élevée", title: "Chaîne distribution B48", description: "Guides fragiles.", dtcRelated: ["P0016","P0340"], repairAction: "Chaîne + guides", datePublished: "2022-08-18" },
    { id: 27, brand: "BMW", model: "i4", years: [2022,2023], source: "RAPPEL_CONSO", severity: "Élevée", title: "Batterie HT surchauffe", description: "Cellule défectueuse.", dtcRelated: ["P0A0A","P0A0B"], repairAction: "Module batterie", datePublished: "2023-04-12" },
    { id: 28, brand: "Mercedes-Benz", model: "GLC (X253)", years: [2017,2018], source: "NHTSA", severity: "Élevée", title: "EGR incendie OM654", description: "Fuite liquide refroidissement.", dtcRelated: ["P0401","P0403","P2015"], repairAction: "Vanne EGR", datePublished: "2022-03-28" },
    { id: 29, brand: "Audi", model: "A4 (B9)", years: [2017,2018], source: "SAFETY_GATE", severity: "Élevée", title: "Chaîne 2.0 TFSI EA888", description: "Bru
